"""create publications tables

Revision ID: 11d5859d5c0c
Revises: 981546fb540d
Create Date: 2025-10-01 23:45:30.799524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d5859d5c0c'
down_revision: Union[str, Sequence[str], None] = '981546fb540d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('publication_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('section_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=True),
    sa.Column('scientist_summary', sa.Text(), nullable=True),
    sa.Column('manager_summary', sa.Text(), nullable=True),
    sa.Column('mission_architect_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summaries')
    op.drop_table('publication_sections')
    op.drop_table('publications')
    # ### end Alembic commands ###
