"""Fix section_summary field

Revision ID: 407514f54b73
Revises: 850423068926
Create Date: 2025-10-03 17:22:07.444653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407514f54b73'
down_revision: Union[str, Sequence[str], None] = '850423068926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_sections', sa.Column('section_summary', sa.Text(), nullable=True))
    op.drop_column('summaries', 'section_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('section_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('publication_sections', 'section_summary')
    # ### end Alembic commands ###
