"""Fix section_summary field

Revision ID: 850423068926
Revises: 989bbe42f7fd
Create Date: 2025-10-03 16:44:39.221676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '850423068926'
down_revision: Union[str, Sequence[str], None] = '989bbe42f7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('section_summary', sa.Text(), nullable=True))
    op.drop_column('summaries', 'section_summarys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('section_summarys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('summaries', 'section_summary')
    # ### end Alembic commands ###
